# Generated by Django 6.0.3 on 2026-03-04 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('boy', 'Мальчик'), ('girl', 'Девочка')], default='boy', max_length=10, verbose_name='Пол')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='children_avatars/', verbose_name='Фото')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('size', models.CharField(max_length=10, verbose_name='Размер (рост)')),
                ('season', models.CharField(choices=[('winter', 'Зима'), ('summer', 'Лето'), ('demi', 'Деми'), ('all_season', 'Всесезон')], default='demi', max_length=20, verbose_name='Сезон')),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('excellent', 'Отличное'), ('used', 'Б/у')], default='new', max_length=20, verbose_name='Состояние')),
                ('status', models.CharField(choices=[('wearing', 'Носим'), ('small', 'Мало'), ('sell_give', 'Продать/Отдать')], default='wearing', max_length=20, verbose_name='Статус')),
                ('photo', models.ImageField(upload_to='clothes_images/', verbose_name='Фото')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.category', verbose_name='Категория')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='core.child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
                'ordering': ['-created_at'],
            },
        ),
    ]
